### ISSUE TITLE
Add Reddio

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#1045]
Reddio (https://www.reddio.com/) is NFT trading Layer2 based on StarkEx Spot Trading v 4.5

Proxy: 0xB62BcD40A24985f560b5a9745d478791d8F1945C
Operator: 0x2e1c08E457F0E0F462Ef99eC9271dc5BfAd88b2a
DAC: 0x4b2Bf1Cb06CB636e8A14540F76c477E61d8B6669
Verifier: SHARP Verifier

**Comment by lucadonnoh** [comment]
it has less than 50$ of TVL, should we add it?

**Comment by lucadonnoh** [comment]
inactive
