### ISSUE TITLE
Feature request: list EVM hardfork version supported for each chains

### ISSUE THREAD

**Issue by hrkrshnn** [l2beat/l2beat#1065]
Many L2s are on older EVM versions, and it's somewhat non-trivial to check what versions they are running. It would be a really nice addition to include this as part of the project page.

**Comment by luke7211** [comment]
Can you provide some examples ? Rollups that aim to be EVM equivalent will fork with the mainnet Ethereum so they will always be up-to-date. Rollups that are not equivalent, but compatible, potentially have all sorts of restrictions that go much deeper than just an EVM version

**Comment by hrkrshnn** [comment]
Sorry about the delay in reply.  @luke7211 

> Rollups that aim to be EVM equivalent will fork with the mainnet Ethereum so they will always be up-to-date

I believe many of them were (and probably still are) on older hardforks. I don't have any resources to point to regarding this, but this many didn't have, for example, `basefee` implemented.

**Comment by lucadonnoh** [comment]
https://www.rollup.codes/ came out with exactly that purpose, we should probably link to the website

**Comment by lucadonnoh** [comment]
just started linking to it 
<img width="769" alt="image" src="https://github.com/l2beat/l2beat/assets/30298476/e2ffd614-3a53-40f1-9eb1-618202f4d906">

**Comment by radeksvarz** [comment]
It is still unclear which solidity target can be used on each particular rollup. Paris? Shanghai? Cancun?
Example - PUSH0 as introduced by Dencun - is it there? https://www.rollup.codes/base#opcodes
