### ISSUE TITLE
Add pNetwork bridge

### ISSUE THREAD

**Issue by MatteoCarbo** [l2beat/l2beat#1100]
Hi everyone,
I'm Matteo from pNetwork.
Would be great if you can add pNetwork bridge to L2Beat!

pNetwork supports 15 blockchains, including several L2 networks.
This [API](https://pnetwork.watch/api/datasources/proxy/1/query?db=pnetwork-volumes-1&q=SELECT%20sum(%22tvl_number%22)%20FROM%20%22tvl_v2%22%20WHERE%20time%20%3E%3D%201600150697388ms%20GROUP%20BY%20time(1d)%2C%20%22host_blockchain%22%3BSELECT%20sum(%22tvl_number%22)%20FROM%20%22tvl_v2%22%20WHERE%20time%20%3E%3D%201600150697388ms%20GROUP%20BY%20time(1d)%20fill(null)&epoch=ms%22) should have everything you need to add the data from our bridge.

I'll be happy to provide further information if needed.

Kind regards,
Matteo

**Comment by luke7211** [comment]
Hey, thank you for the request, please provide basic set of escrow addresses on Ethereum such as e.g. 0x112334f50Cb6efcff4e35Ae51A022dBE41a48135

**Comment by MatteoCarbo** [comment]
For reference, these are the vault contracts on Ethereum safeguarding the L2 TVL of pNetwork:
https://etherscan.io/address/0xe396757ec7e6ac7c8e5abe7285dde47b98f22db8
https://etherscan.io/address/0x9f8622b11984afc8f0a42a394928702017c5968d

Please note that some Etherscan prices might be untruthful for some tokens.

Thank you!
