### ISSUE TITLE
Problem: Sorare project page

### ISSUE THREAD

**Issue by Nadai2010** [l2beat/l2beat#1234]
Hi, the sorare twitter link is wrong, this would be the verified one... 

GOOD: https://twitter.com/Sorare    

BAD: https://twitter.com/sorarehq

And always great work

**Comment by krzkaczor** [comment]
Thanks for raising this issue! We are on it.

**Comment by Nadai2010** [comment]
To you, we all help each other, I added another one in Rhino...Great job of L2 Beat and L2 Spanish
