### ISSUE TITLE
L2 addition: Base from Coinbase

### ISSUE THREAD

**Issue by randomishwalk** [l2beat/l2beat#1241]
[Mirror post on announcement](https://base.mirror.xyz/H_KPwV31M7OJT-THUnU7wYjOF16Sy7aWvaEr5cgHi8I
)

Don't believe technical spec or details / specifics are out yet as of this issue, but could be wrong.

### Quick Summary of Article
Coinbase is launching Base, an Ethereum Layer 2 (L2) network built on the OP Stack, as the second L2 following Optimism Mainnet. Base will serve as the home for Coinbase's onchain products and an open ecosystem for anyone building Ethereum scaling solutions and dapps. Coinbase will work with OP Labs and the Optimism Collective to create a robust developer ecosystem of interoperable L2s and rollups that will help onboard the next billion users into web3. The goal is to create a mesh or Superchain that jointly scales Ethereum and creates a much more vibrant developer ecosystem than what would be possible by a single chain alone. The Superchain will pave the way for greater participation, security, and new use cases. Coinbase, Base, OP Labs, and the Optimism Collective are explicitly furthering the decentralization of decision making and control of the OP Stack and the Superchain by working together.

**Comment by InitialSupport** [comment]
We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6

**Comment by michalsidzej** [comment]
We added Base as an upcoming project [here](https://l2beat.com/scaling/projects/base)
