### ISSUE TITLE
Problem: rhino.fi project page

### ISSUE THREAD

**Issue by Nadai2010** [l2beat/l2beat#1243]
Link Video Youtube is BAD 

Good: https://www.youtube.com/@rhinofi

**Comment by krzkaczor** [comment]
Thanks for another issue! 

Perhaps you want to create a PR and fix it? We have a contributing guide here: https://github.com/l2beat/l2beat/blob/master/CONTRIBUTING.md

**Comment by Nadai2010** [comment]
This is the first test, check if I have done well as a contributor.

https://github.com/Nadai2010/l2beat/blob/master/packages/config/src/layer2s/rhinofi.ts

**Comment by krzkaczor** [comment]
Yup, looks good. You can create a PR now.

**Comment by Nadai2010** [comment]
Perfect, I create it and so anything I add it from there for your review thank you very kindly.

**Comment by Nadai2010** [comment]
Thank you
