### ISSUE TITLE
Feature: Weighted/ranked risk analysis

### ISSUE THREAD

**Issue by hanniabu** [l2beat/l2beat#1277]
While the risk analysis dashboard is hugely useful, it takes an already knowledgeable person to be able to assess it. What I'd love to see is a each category (state validation, data availability, upgradeability, sequencer failure, validator failure) be given a weighted score for risk importance and then provide an overall score for each L2. This way users can interpret/compare the level of risk for an L2 without needing to be knowledgeable on all the technical details.

For example (values not meant to be accurate):

category                     | weight  
---------------------|---------
state validation          |  5
data availability         | 2
upgradeability           | 3
sequencer failure      | 3
validator failure         | 5

state validation           | weight  
---------------------|---------
in development          |  0
fraud proofs.              |  0.5
zkproofs (sn)             | 0.9
zkproofs (st)              |  1

data availability          | weight  
---------------------|---------
external                      | 0
onchain                      |  1

upgradeability           | weight  
---------------------|---------
yes                              | 0
<14 day delay            |  0.6
\>= 14 day delay         |  0.8
no                               |  1

sequencer failure      | weight  
---------------------|---------
no mechanism           | 0
forced exit                  | 0.3
force trade/exit to 1   |  0.3
transact using L1       |  0.8
propose blocks          |  1

validator failure         | weight  
---------------------|---------
no mechanism           | 0
propose blocks          |  0.8
escape hatch             |  1

### Calculations for Optimism

category                    | status                      |  weighted value
---------------------|-------------------|-----------------
state validation          |  in development    | 5 x 0 = 0
data availability         | onchain                   | 2 x 1 = 2
upgradeability           | yes                          | 3 x 0 = 0
sequencer failure      | transact using L1   | 3 x 0.8 = 2.4
validator failure         | no mechanism       | 5 x 0 = 0
total                           |                                 | 4.4

### Results

Max Score = (5 x 1) + (2 x 1) + (3 x 1) + (3 x 1) + (5 x 1) = 18
Optimism Score = 4.4

As a percentage this would be a risk score of 24.4%. This can be inverted to be more intuitive (higher score = higher risk), which would be a risk score of 75.6%.

**Comment by krzkaczor** [comment]
I think you're gonna like what we are cooking here: https://gov.l2beat.com/t/rollup-maturity-ranking-proposal-call-for-final-feedback/119?u=krzkaczor

**Comment by lucadonnoh** [comment]
we evaluated a weighted risk as you proposed but we ultimately decided to support Stages as initially proposed by Vitalik. Check it out: https://medium.com/l2beat/introducing-stages-a-framework-to-evaluate-rollups-maturity-d290bb22befe
