### ISSUE TITLE
Immutable X

### ISSUE THREAD

**Issue by Nadai2010** [l2beat/l2beat#1288]
where you can create a PR, or to add the StarkEx force witdh documents well, since several are wrong and I don't know in which file I modify that part of the erroneous link

https://docs.starkware.co/starkex/spot/spot-trading-full-withdrawals.html

**Comment by claudioantonio** [comment]
@Nadai2010 I understood that you want to add/update links regarding StarkEx's forced exit.
The links for this section in the Immutable X page are broken:
[Forced Operations - StarkEx documentation](https://docs.starkware.co/starkex-v3/starkex-deep-dive/regular-flows/flows-for-off-chain-accounts/forced-operations)
[Forced Withdrawal - StarkEx documentation](https://docs.starkware.co/starkex-v3/starkex-deep-dive/smart-contracts-1/in-spot-trading/in-perpetual-trading)
[Full Withdrawal - StarkEx documentation](https://docs.starkware.co/starkex-v3/starkex-deep-dive/smart-contracts-1/in-spot-trading/in-spot-trading)

If I understood it correctly, you can update/add links regarding it by editing the file `/workspace/packages/config/src/layer2s/common/exits.ts` and submitting a PR.

**Comment by Nadai2010** [comment]
Hi, I did not remember this, sorry, then I saw the change in local and did not perform the PR, it is already uploaded.

**Comment by michalsidzej** [comment]
Closed by https://github.com/l2beat/l2beat/pull/1448
