### ISSUE TITLE
UX Suggestion: Update Risk Analysis chart colors

### ISSUE THREAD

**Issue by dewanshparashar** [l2beat/l2beat#1307]
Great work with the Risk analysis component on L2Beat. It's very insightful!

While the colors yellow/red are good for warning, as a small enhancement, it'd be amazing to see the good/ok parts for all L2s green instead of grey. That would give a much better sense of approval to the audience as green is widely associated to be a happy indicator.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/7558499/226458062-80b2cdbb-ef4a-4935-8cfd-4cdc3de5a31f.png">

**Comment by lucadonnoh** [comment]
wip #1631
