### ISSUE TITLE
Add Layer 3s as Layer2

### ISSUE THREAD

**Issue by sheenhx** [l2beat/l2beat#1778]
Hey

We are the first layer 3 on Arbitrum, using zkEVM, and network is quite stable now.

Can you add us as layer2 if you don't have a separate section yet? 

https://github.com/l2beat/l2beat/pull/1721

**Comment by lucadonnoh** [comment]
we're working on supporting L3s

**Comment by sheenhx** [comment]
@lucadonnoh any update?

**Comment by lucadonnoh** [comment]
nope

**Comment by sheenhx** [comment]
@lucadonnoh any update?
