### ISSUE TITLE
Problem: Honeypot (Cartesi) project page

### ISSUE THREAD

**Issue by diveshpincha** [l2beat/l2beat#1974]
[Catesi's Honeypot dapp](https://honeypot.cartesi.io/) is live , but not reflected on [L2Beat site](https://l2beat.com/scaling/projects/cartesi-honeypot) , still says that is in development.

Clicking the "edit information" redirects to a broken site

**Comment by lucadonnoh** [comment]
adding, thanks for reporting!

**Comment by lucadonnoh** [comment]
added
