### ISSUE TITLE
Milestone "Learn more ->" on mobile is not clickable

### ISSUE THREAD

**Issue by radinat** [l2beat/l2beat#2034]
**To reproduce**
1. Open a project's page **on mobile** (e.g. https://l2beat.com/scaling/projects/arbitrum)
2. Click on a milestone on the chart (the green square on the bottom)
3. Try clicking "Learn more"

**Result**: Cannot click, modal closes
**Expected result**: Should be able to click, the link should be opened.

Investigate the cause and implement a fix. Possible cause: there is `pointer-events-none` class on the `chart-hover-contents` element.

**Comment by Gathin23** [comment]
@radinat Can you assign this to me?

**Comment by radinat** [comment]
Was fixed as part of another task.
