### ISSUE TITLE
Add tooltips for the values in the top section of TVL Breakdown page

### ISSUE THREAD

**Issue by radinat** [l2beat/l2beat#2035]
**Context**

On the TVL Breakdown page in the purple section we show some values with % change but it's not clear what is the period for the % change.

**To do**

Add tooltips next to the values (and make sure they match both light and dark mode colours and the mobile view):
![image](https://github.com/l2beat/l2beat/assets/32281618/0fb6b02c-b8a2-4229-a544-0dfcea5c3f14)
![image](https://github.com/l2beat/l2beat/assets/32281618/ec3e287a-c74a-45f8-9d87-3379c52446cb)

Texts:

- Total Value Locked: Total value locked displayed together with a percentage change compared to 7D ago.
- Canonically Bridged Value: Total value locked in escrow contracts on Ethereum displayed together with a percentage change compared to 7D ago.
- Externally Bridged Value: Total value of externally bridged tokens displayed together with a percentage change compared to 7D ago.
- Natively Minted Value: Total value of natively minted tokens displayed together with a percentage change compared to 7D ago.

**Comment by Gathin23** [comment]
@radinat Can you assign this to me?

**Comment by Gathin23** [comment]
@radinat I have made the necessary changes #2050
