### ISSUE TITLE
Problem: Omnichain (LayerZero) project page - broken link

### ISSUE THREAD

**Issue by randomishwalk** [l2beat/l2beat#2133]
The [edit the information](https://github.com/l2beat/l2beat/edit/master/packages/config/src/bridges/omnichain.ts) link is broken. Think it is supposed to be re-directing towards https://github.com/l2beat/l2beat/blob/master/packages/config/src/bridges/lzOmnichain.ts?

**Comment by mateuszradomski** [comment]
I don't think it's relevant anymore, if it is please re-open this issue.
