### ISSUE TITLE
Consider beginning "bridges value locked" axis at 0

### ISSUE THREAD

**Issue by NiloCK** [l2beat/l2beat#2152]
![image](https://github.com/l2beat/l2beat/assets/10780590/9380df32-3287-461d-8ae4-cf6b52934057)

The above gives an impression of a 90% reduction in TVL between one year ago and the low point. But the high on the graph is ~8B and the low is >4B.

**Comment by lucadonnoh** [comment]
We considered this, but then noticed that all the charts on other websites are doing it exactly in the way we do. What do you think? It would be a bit inconsistent to do things differently.

![image](https://github.com/l2beat/l2beat/assets/30298476/2a116f88-d595-474a-a11d-6e25915355fa)
![image](https://github.com/l2beat/l2beat/assets/30298476/28001121-31a0-406c-8e4b-0a98f6025481)
![image](https://github.com/l2beat/l2beat/assets/30298476/57934899-f39e-4a92-a3d3-cf0448bb71a8)
