### ISSUE TITLE
chart code

### ISSUE THREAD

**Issue by TimDaub** [l2beat/l2beat#223]
Hey, I find our chart on L2Beat quite beautiful and I also noticed that it's using svg. I'm the author of an SVG line chart library: https://github.com/rugpullindex/svg-line-chart I use it to instantly give users a chart upon page load. And looking at yours, I was wondering what library you're using or if it's your implementation.

I'm interested in reading the code. Maybe there's even a chance to collab on a chart lib?

**Comment by sz-piotr** [comment]
I think I'll let you down. The chart does not use SVG. It uses canvas, because it was a lot simpler. You can read the code here:
https://github.com/l2beat/l2beat/blob/ac883e4badef7d1c86f6607ecbb7b82dcae56683/website/src/scripts/chart/plot.ts
