### ISSUE TITLE
use Arbitrum token list json for tokens on Arbitrum

### ISSUE THREAD

**Issue by DZGoldman** [l2beat/l2beat#224]
https://bridge.arbitrum.io/token-list-42161.json (which we host) has all of the tokens bridged onto Arbitrum; if you dynamically fetched the list from there (instead of [hardcoding it](https://github.com/l2beat/l2beat/blob/ac883e4badef7d1c86f6607ecbb7b82dcae56683/config/src/projects/arbitrum.ts#L15)) we would never have to bother you about updating it :)

**Comment by DZGoldman** [comment]
...also as a lazy / immediate-term improvement, can just use that as a reference point to add any / all to the hardcoded list. Currently, top tokens by value on Arbitrum not on your hardcoded list are USDT, DODO, BAL, MCB, LAND, SUSHI, and UNI

**Comment by joshuacolvin0** [comment]
Created #230 for an immediate term improvement.

**Comment by krzkaczor** [comment]
We decided to follow our current strategy of only tracking "important enough" tokens with decent liquidity etc.
