### ISSUE TITLE
Add Unverified Smart Contracts warning to the summary page

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#225]
Unverified Smart Contracts should be considered a major no-no in our space. Nobody except from in-the-know devs and testers should ever use contracts that are unverified. If the Rollup is using even a single unverified smart contract, we should display the big red warning in the summary page to attract user (and developers team) attention

**Comment by luke7211** [comment]
This tx https://ethtx.info/0x924fbc366dc7cfee30d285cdd1f5c085a817f423bc0b6f50107f7c8eaf87cd42/ is from dYdX, most contracts are verified, but https://etherscan.io/address/0x89bb5527834385ac440732d35e8fd501ececa560 is not

**Comment by krzkaczor** [comment]
Closing in favor of linear.
