### ISSUE TITLE
Polygon zkEVM TVL

### ISSUE THREAD

**Issue by biafffff** [l2beat/l2beat#2280]
I was checking the Polygon zkEVM TVL and I see a significant difference btw what I see on L2beat vs DeFiLlama

* L2beat shows ~$106m deposited
* [DeFiLlama](https://defillama.com/chain/Polygon%20zkEVM) shows ~$27m deposited

Can it be related to the way [L2beat computes the TVL](https://l2beat.com/faq#how-exactly-do-you-calculate-metrics-like-tvl:~:text=Optimiums%20for%20clarity.-,How%20exactly%20do%20you%20calculate%20metrics%20like%20TVL%3F,-It%20varies%20from) that differs from the method used by DeFiLlama or is it an error?

![image](https://github.com/l2beat/l2beat/assets/26275332/dc6468e4-f68b-4d80-ab16-e5e4aea0fce2)

![image](https://github.com/l2beat/l2beat/assets/26275332/2d22895a-7f46-4978-8ef9-7fab3ae438dc)

**Comment by lucadonnoh** [comment]
read here https://l2beat.com/faq#why-does-the-total-value-locked-tvl-on-l2beat-differ-from-the-one-on-defillama
