### ISSUE TITLE
zkSync risk upgradability period

### ISSUE THREAD

**Issue by dzid26** [l2beat/l2beat#237]
Per https://medium.com/matter-labs/keeping-funds-safe-a-3-factor-approach-to-security-in-zksync-2-0-a70b0f53f360#e655 the upgradibility poeriod is 4 weeks not [2 weeks](https://l2beat.com/?view=risk). 
![image](https://user-images.githubusercontent.com/841061/132411487-bccc65bb-36d8-48a7-a41d-bd1bad604038.png)

**Comment by sz-piotr** [comment]
I belive that the blog post is incorrect.
This is the ZkSync proxy contract: https://etherscan.io/address/0xaBEA9132b05A70803a4E85094fD0e1800777fBEF#readProxyContract
This is the implementation:
https://etherscan.io/address/0xd61dff4b146e8e6bdcdad5c48e72d0ba85d94dbc#code

In ZkSync there is a very non-standard mechanism for defining delays. However ignoring how the delay is achieved the value is specified in the following code: 
```solidity
    /// @dev Expiration delta for priority request to be satisfied (in seconds)
    /// @dev NOTE: Priority expiration should be > (EXPECT_VERIFICATION_IN * BLOCK_PERIOD)
    /// @dev otherwise incorrect block with priority op could not be reverted.
    uint256 internal constant PRIORITY_EXPIRATION_PERIOD = 3 days;

    /// @dev Reserved time for users to send full exit priority operation in case of an upgrade (in seconds)
    uint256 internal constant MASS_FULL_EXIT_PERIOD = 9 days;

    /// @dev Reserved time for users to withdraw funds from full exit priority operation in case of an upgrade (in seconds)
    uint256 internal constant TIME_TO_WITHDRAW_FUNDS_FROM_FULL_EXIT = 2 days;

    /// @dev Notice period before activation preparation status of upgrade mode (in seconds)
    /// @dev NOTE: we must reserve for users enough time to send full exit operation, wait maximum time for processing this operation and withdraw funds from it.
    uint256 internal constant UPGRADE_NOTICE_PERIOD =
        MASS_FULL_EXIT_PERIOD+PRIORITY_EXPIRATION_PERIOD+TIME_TO_WITHDRAW_FUNDS_FROM_FULL_EXIT;
```
Link to the source code on Etherscan:
https://etherscan.io/address/0xd61dff4b146e8e6bdcdad5c48e72d0ba85d94dbc#code#F8#L84

@gluk64 Can you confirm?

**Comment by dzid26** [comment]
Thanks for checking the contract. 

It seems that the timelock is planned to be increased: https://zksync.io/faq/security.html#upgrade-mechanism :
> NOTICE: Currently, the beta is deployed with a 2-week notice period, and eventually will be bumped to 4 weeks. In the future, this opt-out mechanism will be replaced by a strict opt-in.
For interested people, Alex talked a bit about zkSync (V2) security in this podcast:
https://www.crowdcast.io/e/pod-zksync/clips/61389cae443cb60096721121

(Also I noticed that at present the timelock is bumped to 18days total as the `PRIORITY_EXPIRATION_PERIOD` [was increased ](https://github.com/matter-labs/zksync/commit/cfaceaeb48f0121221a66b7b79d23e1ae587c92c)to 7 days. I am assuming this is not final. )

**Comment by sz-piotr** [comment]
Good catch with the increase in the source code. When zkSync updates on chain contracts with this new code we'll also update the data on L2BEAT.

**Comment by krzkaczor** [comment]
We are planning on automating some of the metrics, this included.
