### ISSUE TITLE
Clearly differentiate between intent and implementation risk on the summary page

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#242]
Right now it's not visually clear that, for example Optimism is using Fraud Proofs, or that it is possible, when Operator is down for users to submit state batch and relay L2 -> L1 message themselves. Maybe the text for State validation should say "Fraud proofs" with red colour and hint "Currently disabled". Similarly the "Operator Down" - can be explained that it is possbile, however right now only Sequencer and Relayer can push tx on L1 and relay them

**Comment by krzkaczor** [comment]
I think this is done with updated risk framework. Reopen if needed.
