### ISSUE TITLE
Prove dYdX is a rollup

### ISSUE THREAD

**Issue by sz-piotr** [l2beat/l2beat#249]
There were some concerns raised on Twitter. Find out where the data is stored on chain.

**Comment by luke7211** [comment]
updateState() for dYdX contains state diffs of user's balances
https://etherscan.io/address/0xdf9c117cad37f2ed8c99e36a40317d8cc340d4a0#code#F35#L82

updasteState() for DeversiFi contains data availability proofs (essentially a collection of sigs from data availability commitee promising that they hold user's balances)
https://etherscan.io/address/0x86d8f977c9cec503ad4e6805802cef62cde13773#code#F34#L126
