### ISSUE TITLE
📌 L2BEAT Roadmap 09.2021

### ISSUE THREAD

**Issue by sz-piotr** [l2beat/l2beat#252]
This document outlines our focused tasks for L2BEAT starting September 2021. It minimally indicates intent to investigate tasks or contribute to an implementation. Nothing is set in stone, but we will strive to complete these tasks in a reasonable timeframe.

## Architecture changes
- [Move to a server backend](https://github.com/l2beat/l2beat/issues/248) (*CURRENTLY IN PROGRESS*)
- [Update stats every hour](https://github.com/l2beat/l2beat/issues/244)
- [Automatically fetch recent news](https://github.com/l2beat/l2beat/issues/251)

## Frontend improvements
- [Store chart state in the URL](https://github.com/l2beat/l2beat/issues/171)
- [Add x-axis labels to the chart](https://github.com/l2beat/l2beat/issues/175)
- [Make the table sortable](https://github.com/l2beat/l2beat/issues/219)
- [Enable per branch frontend builds](https://github.com/l2beat/l2beat/issues/250)

## Research
- ~[Prove dYdX is a rollup](https://github.com/l2beat/l2beat/issues/249)~
- [Investigate Aztec smart contracts](https://github.com/l2beat/l2beat/issues/243)

**Comment by stefment** [comment]
Would you be interested in some sort of crawler that tracks how many nodes/validators are involved with each rollup? The reason i am asking is because i saw Optimism refer to itself as a network today, and so i was wondering how many nodes there are
