### ISSUE TITLE
Make the "Log" vs. "Linear" selection for the graph axis persistent

### ISSUE THREAD

**Issue by A2be** [l2beat/l2beat#260]
A month or two ago, L2beat added a selection button to enable a _Logarithmic_ scale on the y-axis.  This is super useful.  Thanks.

But as it stands, the web app resets the axis view to _Linear_ every time the page is opened, or refreshed.

This forces the user to have to manually reselect the "Log" view each time if they prefer logarithmic scales.  

(_personal opinion_:  log scales are vastly better than linear scales for properly analyzing exponential growth, which a very great deal of blockchain adoption data is.  E.g., growth in overall L2 TVL in the recent week/month; or the growth of Arbitrum L2 in any reasonable time period now.)
But hey, let's make it user-selectable, _and persistent_.

Could you consider **adding a way to store the user choice used on the L2beat.com website to be persistent?**  A non-tracking cookie?  Or something else?

**Comment by sz-piotr** [comment]
That is a good suggestion. I wanted to store the state in the URL as per #171, because that would make it shareable - similar to how on the main page the URL changes when you switch to risk view.
