### ISSUE TITLE
List of 404's across the project

### ISSUE THREAD

**Issue by stavares843** [l2beat/l2beat#2623]
List of url's that are used across the project and are returning 404.

| Status          | URL                                                         | Source link text                                        |
|-----------------|-------------------------------------------------------------|---------------------------------------------------------|
| 404 Not Found   | https://market.x.immutable.com/                             | [App](https://l2beat.com/scaling/projects/immutablex)                                                     |
| 404 Not Found   | https://docs.starkware.co/starkex-docs-v2/                  | [Docs](https://l2beat.com/scaling/projects/immutablex)                                                    |
| 404 Not Found   | https://docs.starkware.co/starkex-v3/architecture/overview  | [Censorship Prevention - StarkEx documentation](https://l2beat.com/scaling/projects/immutablex)          |
| 404 Not Found   | https://boba.network/boba-network-multichain-announcement/  | [Learn more](https://l2beat.com/scaling/projects/bobanetwork)                                              |
| 404 Not Found   | https://boba.network/Boba-airdrop-live/                     | [Learn more      ](https://l2beat.com/scaling/projects/bobanetwork)                                        |
| 404 Not Found   | https://github.com/kroma-network/kroma/blob/main/specs/differences-from-optimism-bedrock.md  | [here](https://l2beat.com/scaling/projects/kroma)  |
| 404 Not Found   | https://www.brine.fi/beta-launch                             | [Learn more        ](https://l2beat.com/scaling/projects/tanx)                                      |
| 404 Not Found   | https://l2beat.com/mask-icon.svg                             | [link/href ](https://l2beat.com/scaling/summary)                                              |

**Comment by m-posluszny** [comment]
I'd like to help with that

**Comment by varun-doshi** [comment]
I'd like to work on this. 
Can it be assigned to me?

**Comment by mabsattar** [comment]
Hi, I would like to contribute.

**Comment by mateuszradomski** [comment]
![image](https://github.com/l2beat/l2beat/assets/33978857/37e0fa17-f329-4844-887e-be9901f23ddf)
