### ISSUE TITLE
Upgradability of Polygon Hermez is potentially inaccurate

### ISSUE THREAD

**Issue by SteveHere** [l2beat/l2beat#340]
A question was raised on Polygon's Discord server, to which one of the responses from the team was:
https://discord.com/channels/635865020172861441/910852199905624124/914840921814732851

![image](https://user-images.githubusercontent.com/13937978/143861592-80aecefb-0d5c-415b-b97c-8d0f1ca31b00.png)

According to the response that I've received for my initial question, the `delay` variable for the following smart contract is responsible for the upgradability delay:

https://etherscan.io/address/0xf7b20368Fe3Da5CD40EA43d61F52B23145544Ec3#readContract

604800 / 86400 = 7

If this is the case, the Upgradeability of Polygon Hermez needs to be changed from 'Yes' to '7 days delay'.

**Comment by sz-piotr** [comment]
Fixed in #341
