### ISSUE TITLE
Add StarkNet

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#342]
https://medium.com/starkware/starknet-alpha-now-on-mainnet-4cf35efd1669

**Comment by luke7211** [comment]
StarkNet Alpha was launched on the 12th of Nov and announced on the Nov 29th (https://medium.com/starkware/starknet-alpha-now-on-mainnet-4cf35efd1669) 

Unless standard bridging will be available, there is no way to track TVL nor there is a way for users to access DApps. Dapp deployment is possible only for whitelisted projects. In the alpha there are no fees.

**Comment by rootulp** [comment]
[l2beat/starknet](https://l2beat.com/projects/starknet/) appears to exist now. It looks like https://github.com/l2beat/l2beat/pull/351 may have resolved this issue. Defer to @luke7211 if there is anything else to be added.
