### ISSUE TITLE
Switch from coinpaprika to coingecko for datapipeline

### ISSUE THREAD

**Issue by krzkaczor** [l2beat/l2beat#36]
* Coinpaprika misses some tokens
* There are "holes" in data

**Comment by gasolin** [comment]
Maybe replaceable by `get_coin_history_by_id()` https://pypi.org/project/pycoingecko/
https://github.com/man-c/pycoingecko/blob/master/pycoingecko/api.py#L144

I could send PR to add `coingecko_id` in the config once https://github.com/krzkaczor/l2beat/pull/41 is merged

**Comment by krzkaczor** [comment]
Hey, thanks for expressing your interest in working on this but we are planning on rewriting the whole pipeline to a more modular approach and probably we will write it in JS. I would prefer not to change the current impl.

**Comment by gasolin** [comment]
I made a script to fetch l2 contracts TVL, 
can refer here https://github.com/gasolin/ethhole/blob/main/scripts/fetch_data.js
The result can be viewed in http://gasolin.idv.tw/ethhole/
No history tickers though

**Comment by sz-piotr** [comment]
Closing as we are using coingecko after the rewrite
