### ISSUE TITLE
Include L2 native tokens as part of TVL calculation

### ISSUE THREAD

**Issue by smartcontracts** [l2beat/l2beat#368]
We're starting to see the creation of tokens that are native to L2 systems that don't necessarily have corresponding L1 tokens. Currently, L2Beat only seems to track the value of ETH + ERC20 tokens locked up in the various token bridges for the project. If L2 native tokens aren't considered as part of the TVL, this could create a perverse incentive for projects to create the token on L1 and send the full balance to L2 simply to increase TVL numbers on L2Beat. I think L2 native tokens will become more and more popular, and ultimately they do represent valid TVL and should be represented on L2Beat.

**Comment by smartcontracts** [comment]
I still think L2 native tokens should have to pass the basic requirements (mainly top 300 coingecko), but at least the infrastructure should exist for including these tokens.

**Comment by luke7211** [comment]
Finding a good metric for including a token is very tricky. You want to include tokens that seems to be very legit, like LYRA on Optimism, but at the same time, you don't want meme tokens like HOKK which, if bridged to any L2, would inflate TVL of that L2 to trillions of dollars. 

Tracking native L2 tokens require some architectural changes to L2Beat backend, and it should be done. But the issue remains - which tokens should be included. I would welcome more community input on this issue.

**Comment by smartcontracts** [comment]
I agree that it's important to create a reasonable standard. I'm not sure what the best approach here is. I'll do some thinking about this.

**Comment by luke7211** [comment]
If we take LYRA as an example, there are some further problems to consider:

- It is a fixed supply token (1B) issued on L1, which should make things easier, but ...
- CS (Circulating Supply) is unknown, CMS claims that self-reported CS is 65M, just 6.5%
- 10% of supply was bridged to L2, presumably to distribute rewards to L2 users of Lyra. How much of it is CS is unknown
- Point is - even with token minted on L1 with fixed supply we have no idea how much of that 10% of supply that is bridged to L2 is in circulation. Ignoring CS will lead to ridiculous numbers, accounting for CS is very hard if not impossible

**Comment by lucadonnoh** [comment]
closing as we are reworking TVL
