### ISSUE TITLE
Some comments re: token listing requirements

### ISSUE THREAD

**Issue by smartcontracts** [l2beat/l2beat#370]
I think there are a few issues with the current token listing requirements. Here's the text:

https://github.com/l2beat/l2beat/blob/973cc8f4347b595f431c3b0abd369e44df2230e8/packages/config/src/tokens.ts#L10-L20

The primary issue here is that this list should be filtered according to the rules before being included in the TVL metrics. Otherwise we get into situations where tokens can be entered into the list while they're in the top 300 on coingecko but then stay in the list when they drop below that position. This may create an inflated TVL. Furthermore, this means that some projects can have tokens in their TVL that are below the top 300 but other projects cannot include new tokens that are below the top 300. 

My main recommendation here is to filter the list of tokens by the metrics used in the requirements before displaying these tokens as part of TVL on L2Beat. Otherwise certain projects can have classes of tokens listed that other projects can't.

**Comment by sz-piotr** [comment]
Absolutely agree. Recently #393 has updated the list to include the tokens that fit the requirements and drop others that were included but no longer fit them.

As according to my knowledge this is now resolved I'm closing the issue.
