### ISSUE TITLE
Problem: Aztec - Users can force any transaction

### ISSUE THREAD

**Issue by haniaki** [l2beat/l2beat#387]
anyone can submit the block to the layer 1 (in a periodic window)? what about the proof generation? is that centralized and particular for the operators? and if yes, what if the operator does not prove the block uploaded by anyone else?

**Comment by lucadonnoh** [comment]
the proof generation service is open source: https://github.com/AztecProtocol/aztec-connect/tree/master/yarn-project/halloumi
