### ISSUE TITLE
https://api-staging.eltwobeat.com/api/tvl2/breakdown status: 404, message: Not Found

### ISSUE THREAD

**Issue by sameplacewei** [l2beat/l2beat#4191]
I cloned l2beat website ,run the following commands in sequence. At the last step, the following error occurs

> yarn
> yarn build:frontend
> cd packages/frontend
> yarn start
errors:
Error: Could not get data from api (url: https://api-staging.eltwobeat.com/api/tvl2/breakdown, status: 404, message: Not Found)
    at JsonHttpClient.fetchJson (/home/weizp/work/gows/src/github.com/arcology-network/l2beat/packages/frontend/src/build/caching/JsonHttpClient.ts:24:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchTvlBreakdownApi (/home/weizp/work/gows/src/github.com/arcology-network/l2beat/packages/frontend/src/build/api/fetchTvlBreakdownApi.ts:22:16)
    at async Promise.all (index 3)
    at main (/home/weizp/work/gows/src/github.com/arcology-network/l2beat/packages/frontend/src/build/buildPages.ts:63:9)

 Does anyone know why that is? Thanks

**Comment by torztomasz** [comment]
I guess you cloned our repo when we had the wrong URL set for breakdown API. You should pull the origin/main and it should work by now.

**Comment by sameplacewei** [comment]
Thank you very much for your feedback. But I, as you said clone https://github.com/l2beat/l2beat.git, new problems appeared.

> FetchError: Invalid response body while trying to fetch https://api-staging.eltwobeat.com/api/tvl?excludeAssociatedTokens=true: Premature close
>     at Gunzip.<anonymous> (/home/weizp/work/gows/src/github.com/l2beat/l2beat/node_modules/node-fetch/lib/index.js:400:12)
>     at Gunzip.emit (node:events:529:35)
>     at Gunzip.emit (node:domain:489:12)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   type: 'system',
>   errno: 'ERR_STREAM_PREMATURE_CLOSE',
>   code: 'ERR_STREAM_PREMATURE_CLOSE'
How do we fix this? Thank you.

**Comment by sameplacewei** [comment]
Thanks for your feedback, I solved the problem according to the way you said
