### ISSUE TITLE
[Request] Display settlement frequency

### ISSUE THREAD

**Issue by mmagician** [l2beat/l2beat#4264]
To find out how often the rollups settle onto L1, one currently needs to dive into the transaction history. It's not always immediately obvious which contract to check without diving deep into the weeds.
I'd like to propose adding a section "Settlement", or potentially place this under "Onchain costs", where the settlement frequency of the chain would be displayed.

**Comment by lucadonnoh** [comment]
what about this? https://l2beat.com/scaling/liveness

**Comment by lucadonnoh** [comment]
no it’s because they use state diffs instead of tx data for DA which are usually posted with the proof or if posted before have no meaning until then
