### ISSUE TITLE
Allow switch between USD or ETH denominated TVL

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#45]
As TVL in USD varies depending on the coin price (in USD), sometimes a better metric is to use ETH as quote currency. This is especially true for Rollups that take only ETH (like ImmutibleX). OTOH dYdX takes only USDC as a deposit, so USD is a better quote currency. More generic Rollups that take many tokens may benefit further from token breakdown, but initially switch between USD/ETH should add a lot of insight

**Comment by krzkaczor** [comment]
What DeFi pulse does is that they allow displaying only ETH locked. I think it makes more sense rather than *recalculating* TVL to ether. We could do the same for DAI and USDC (or generally stablecoins).

**Comment by sz-piotr** [comment]
Closing as this is already implemented. Users can now see the TVL denominated in USD or ETH as well as see individual token balances on project page.
