### ISSUE TITLE
need more clarification

### ISSUE THREAD

**Issue by sheenhx** [l2beat/l2beat#4560]
Hey

Please exlain more why you remove MXC : https://github.com/l2beat/l2beat/pull/4494

Moonchain.com has the bridge and prover on Arbitrum and it is a layer 3 supported by OKX, kucoin, crypto.com natively.

@sekuba

**Comment by sekuba** [comment]
Heyo,

Thanks for asking.
Your creation of this issue is sufficient to get our attention, please in the future do not disperse your comments in multiple threads.

The arguments for removing MXC are the following:
1. We did not find any verified/finalized blocks ([only proposals](https://arbiscan.io/address/0x54D8864e8855A7B66eE42B8F2Eaa0F2E06bd641a#readProxyContract#F16))
2. MXC token is ~100% of the chain's TVL, and is exclusively withdrawn through the bridge contract on Ethereum without referencing the L3 state (`onlyAdmin` function)

This does not meet our requirements for an L2/L3 chain and became apparent only when your contracts were verified on chain.

**Comment by sheenhx** [comment]
> Heyo,
> 
> Thanks for asking. Your creation of this issue is sufficient to get our attention, please in the future do not disperse your comments in multiple threads.
> 
> The arguments for removing MXC are the following:
> 
> 1. We did not find any recent verified/finalized blocks ([only proposals](https://arbiscan.io/address/0x54D8864e8855A7B66eE42B8F2Eaa0F2E06bd641a#readProxyContract#F16))
> 2. MXC token is ~100% of the chain's TVL, and is exclusively withdrawn through the bridge contract on Ethereum without referencing the L3 state (`onlyAdmin` function)
> 
> This does not meet our requirements for an L2/L3 chain and became apparent only when your contracts were verified on chain.

Thank you for your thorough review. We understand your concerns and would like to provide additional context:

1. Current state: We are in an early deployment phase, focusing on infrastructure setup and testing. The lack of finalized blocks is temporary as we're establishing the network, there will be more finalized blocks as the network grows. I suggest to note this in our L3 page.
2 Roadmap: We plan to transition to finalized blocks and a more decentralized validator set by the end of 2024. This will address the concerns about proposals vs. finalized blocks.
3. MXC token and bridge: The current admin-only bridge function is a temporary security measure during this early stage. We are developing a more decentralized bridging mechanism that will reference the L3 state, scheduled for implementation by 2024.
4. USDC/ USDT bridged: https://explorer.moonchain.com/token/0x83088a4e43617E020fB5F4D12eB2b4cbeD00A08E
https://explorer.moonchain.com/token/0x8e8Da483593f38237bA11dbeFc0B428B833bc807
https://explorer.moonchain.com/token/0x6688D8D4D6ee2f901A801D44822B5C69F97f3517
https://arbiscan.io/tx/0x8d6b552f4b792f32756182fe58534e276dec8ae994540534aba287c310bab1e7
https://arbiscan.io/tx/0x3f0c1648fbaed5235ff9abbca2a78e1ece5cf073795a6be1cfc79c5b0ee5fa6a
https://arbiscan.io/tx/0xa4f90b7bfcc8f0c819ffb2f4f72acfbe1819ff73be3eff3220023d50ab017447
These are the bridged USDC/USDT/DAI from Arbitrum L2, they can't be withdrawn by admins.

5. Unique features: Our L3 solution offers DePIN launchpads like Blueberryring.com that distinguish it from other L2/L3 solutions.

Given these points, we propose a review for the point 1 and 2 with these additional information highlighted in your website. We're committed to meeting L2beats' requirements and would appreciate the opportunity to demonstrate our progress.

**Comment by sekuba** [comment]
Thanks for the info, we can offer to review again as soon as there are verified blocks and canonical bridging activity, just ping us here ;)

**Comment by sheenhx** [comment]
Thank you for your feedback. We appreciate your willingness to review our project again. I'd like to provide some additional context and clarification:

1. Verified Blocks: While we currently have proposed blocks, our system is designed as a Layer 3 solution on top of Arbitrum. In our L3 architecture, proposed blocks are effectively final once they're submitted to the L2 (Arbitrum). We're working on improving block visibility and verification processes to meet your standards.

2. Native Token for Gas: As a Layer 3 solution, our architecture differs slightly from typical Layer 2 systems. Using our native token (MXC) for gas fees is a deliberate design choice for our L3, which is common in many L3 implementations. This approach allows for more efficient operations within our ecosystem.
3. Open Source Implementation: Our client software implementation is open-source and available for review at https://github.com/MXCzkEVM/mxc-client. This demonstrates our commitment to transparency and allows for community scrutiny of our codebase.
4. Ongoing Development: We're continuously improving our system. The current state represents an early stage of our Layer 3 implementation, and we're actively working on enhancements to meet industry standards and best practices.
Given these points, we kindly request reconsideration for inclusion in L2beats, perhaps with appropriate notes about our Layer 3 status and ongoing development. We're open to further discussions and can provide regular updates on our progress.

We'd be happy to schedule a more detailed technical review to address any specific concerns or questions you may have about our Layer 3 implementation on Arbitrum. This could help clarify how our proposed blocks function in the context of a L3 solution and how they relate to finality on the underlying L2.

Please let us know if you need any additional information or if you'd like to set up a more in-depth technical discussion. We're committed to meeting the high standards of L2beats and contributing positively to the scaling solution ecosystem for DePIN.

**Comment by sekuba** [comment]
Thanks,

Only 2 questions:

1. Are you going to verify blocks in any way in the future? (like e.g. Taiko does with SGX, ZK, Gov, ...)
2. Are you going to use state information for withdrawals in the future?

If you will do either, we will wait until they are fully implemented and then review them.
Please also mind that our capacity to review such extensive forks as yours is limited and we thus automatically prioritize widely-used stacks and minimal forks. This will result in delays for your review in the future.

**Comment by sheenhx** [comment]
Hi Sekuba,

Thanks for your prompt answer, yes we will use Taiko codes as well as we also contribute to it.

Can you add us back to "Archived projects" instead of deleting? You can also note our today's discussion.

**Comment by sekuba** [comment]
We are listing you in upcoming for now (archived would need a full review). #4584

**Comment by sheenhx** [comment]
Thank you for your valuable feedback and the productive discussion. I appreciate your insights and will certainly keep you updated on the progress of the items we discussed.
