### ISSUE TITLE
Explain the difference between L1 and L2 

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#48]
There is a lot of confusion in the community about what should be called an L2. The intention of l2beat.com is to provide transparent and verifiable info about the state of "L2" for Ethereum L1 chain. Other blockchains (e.g. Solana, Avalanche, Fantom, BSC, Polychain, etc...) are L1s. The main page of l2beat.com should explain the approach and the difference clearly

**Comment by sz-piotr** [comment]
Closing as this is reflected in the FAQ
