### ISSUE TITLE
Group the projects by L2

### ISSUE THREAD

**Issue by nesbocaj** [l2beat/l2beat#50]
Currently the projects list seems to be mixing L2s (Optimism, zkSync, etc.) and L2 projects (dYdX and ImmutableX). Instead I suggest that the projects be grouped by L2, like in the following "mockup":

| &nbsp; | NAME             | VALUE LOCKED | MARKET SHARE | TECH                  |    1 DAY % |
| -----: | :--------------- | -----------: | -----------: | :-------------------- | ---------: |
| **1.** | **Loopring**     | **$200.42M** |   **60.37%** | **zk-rollup**         | **+8.72%** |
| **2.** | **Optimism**     | **$106.47M** |   **32.07%** |                       | **+9.84%** |
|        | &emsp;Synthetix  |   $106.47M   |     32.07%   | optimistic rollup     |   +9.84%   |
| **3.** | **StarkEx**      |  **$15.29M** |    **4.61%** |                       | **+4.30%** |
|        | &emsp;DeversiFi  |    $??.??M   |      ?.??%   | validium              |   +?.??%   |
|        | &emsp;dYdX       |    $14.73M   |      4.44%   | zk-rollup             |   +4.60%   |
|        | &emsp;ImmutableX |   $561.32K   |      0.17%   | zk-rollup             |   -7.97%   |
| **4.** | **zkSync**       |   **$9.24M** |    **2.78%** | **zk-rollup**         | **+3.57%** |
| **5.** | **Aztec**        | **$534.08K** |    **0.16%** |                       | **+6.41%** |
|        | &emsp;zk.money   |   $534.08K   |      0.16%   | zk-rollup             |   +6.41%   |
| **6.** | **Fuel**         |    **$4.22** |    **0.00%** | **optimistic rollup** | **-0.17%** |

NB: Despite not having the DeversiFi numbers, I added it as an example that tech can vary for the same L2.

I guess you could also add "validium, zk-rollup" to the StarkEx row, but I'm not sure whether or not that would improve readability of the list:

| &nbsp; | NAME             | VALUE LOCKED | MARKET SHARE | TECH                    |    1 DAY % |
| -----: | :--------------- | -----------: | -----------: | :---------------------- | ---------: |
|  ...   |                  |              |              |                         |            |
| **3.** | **StarkEx**      |  **$15.29M** |    **4.61%** | **validium, zk-rollup** | **+4.30%** |

**Comment by michalsidzej** [comment]
This issue has been resolved. Right now we no longer display L2 projects like Synthetix, but we have decided to keep StarkEx projects separately, as they use different L1 contracts. We added a provider badge in the technology column to indicate where the code is coming from. 
<img width="593" alt="Screenshot 2023-05-17 at 08 22 31" src="https://github.com/l2beat/l2beat/assets/38423054/7e3e55f9-8613-4a4c-bab0-2ef7f9755efb">
