### ISSUE TITLE
Update classification to some projects (zkRollups vs Validium)

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#66]
Clearly differentiate between zkRollups and Validium architectures:
* ImmutableX is Validium not zkRollup
* zkSwap is likely to be Validium as well
* add DeversiFi (which is a Validium)
Update "Learn about Layer2" with reference to articles explaining Rollups vs Validium, etc...

**Comment by sz-piotr** [comment]
Done as of #88
