### ISSUE TITLE
Problem: Orbiter project page

### ISSUE THREAD

**Issue by BartBral** [l2beat/l2beat#827]
Orbiter finance also has USDT supported.

Orbiter EOA-addresses:        

ETH:
0x80c67432656d59144ceff962e8faf8926599bcf8

USDC:
0x41d3d33156ae7c62c094aae2995003ae63f587b3

USDT:
0xd7aa9ba6caac7b0436c91396f22ca5a7f31664fc

ETH To StarkNet (contract address):
0xD9D74a29307cc6Fc8BF424ee4217f1A587FBc8Dc

Chains supported at this moment are:
• ETH-mainnet
• Arbitrum
• Arbitrum-Nova
• zkSync
• StarkNet
• Polygon
• Optimism
• Loopring
• Metis 
• dYdX
• ZKSpace
• Boba
• Immutable-X
• BSC-mainnet

**Comment by luke7211** [comment]
Hey @BartBral , would you consider adding additional information ? Description, links, explanation how the bridge operates, what are the trust assumptions, etc...

**Comment by BartBral** [comment]
Hi there, 
Because I'm not part of the Orbiter team and just one of their Discord moderators, I can only give you some information that they have already shared publicly.

I am not a smart-contract programmer/auditor. Therefore I have no knowledge about Trust-assumptions nor exact technical terms for bridging protocols. The info I learned is from your own L2-BEAT website and articles... that is, the parts I could comprehend.

Orbiter is still in Alpha, and hasn't been audited yet (as far as I am aware of) And the SPV-contracts that Orbiter uses are as far as I know not open-sourced yet, until they are ready to go to at least Beta-stage.

================================

Twitter: https://twitter.com/orbiter_finance
Medium: https://orbiter-finance.medium.com

Discord: https://discord.gg/orbiter-finance
    Discord user name: orbiter#9002
    Discord user-ID: 847720053465153547

User docs: https://docs.orbiter.finance

Source code: https://github.com/orbiter-finance

================================

Orbiter EOA ETH-address:
0x80c67432656d59144ceff962e8faf8926599bcf8

Orbiter bridges ETH on:
• ETH-mainnet
• zkSync
• Polygon
• Arbitrum
• Arbitrum-Nova
• Loopring
• Optimism
• ZKSpace
• Immutable X
• Metis Andromeda
• Boba
• StarkNet
• BNB-chain

-------------------------

Orbiter EOA USDC-address:
0x41d3d33156ae7c62c094aae2995003ae63f587b3

Orbiter bridges USDC on:
• ETH-mainnet
• zkSync
• Polygon
• Arbitrum
• Arbitrum-Nova
• Optimism
• dYdX

-------------------------

Orbiter EOA USDT-address:
0xd7aa9ba6caac7b0436c91396f22ca5a7f31664fc

Orbiter bridges USDT on:
• ETH-mainnet
• zkSync
• Polygon
• Arbitrum
• Optimism

================================

Feel free to ask me for specific info, if you think I can be of any help.
But I would recommend asking Orbiter directly on one of their socials.


Have a good day, and thanks for l2beat.com

**Comment by BartBral** [comment]
Yesterday Orbiter finance added DAI to the assets:

Orbiter EOA DAI-address:
0x095D2918B03b2e86D68551DCF11302121fb626c9

Orbiter bridges DAI on:
• ETH-mainnet
• StarkNet
• Arbitrum
• Optimism
• Polygon
• zkSync
