### ISSUE TITLE
Rainbow Bridge: fix bridge type

### ISSUE THREAD

**Issue by sept-en** [l2beat/l2beat#854]
Rainbow Bridge is currently described as the "Token Bridge". However, the bridge is rather a "Generic Bridge" as it also allows transferring arbitrary messages between chains and validating them the same way they are being validated for tokens - using light client proofs.

**Comment by alexauroradev** [comment]
The bridge can be used to transfer anything that is proovable with the light client:

1. Any contents of the block headers (including block hashes, etc.)
2. Anything that is merkelized (including txs, logs, storage), since merkle roots are present in the block header
