### ISSUE TITLE
Rainbow Bridge: update risks

### ISSUE THREAD

**Issue by sept-en** [l2beat/l2beat#855]
Rainbow Bridge has a [Smart Contract](https://l2beat.com/bridges/projects/near/#contracts) section that has _"Funds can be stolen if a contract receives a malicious code upgrade. There is no delay on code upgrades (CRITICAL)."_ statement. The statement is not applied in this case as these contracts are non-upgradeable.

**Comment by alexauroradev** [comment]
Ethereum-side contracts are located here:

### Mainnet
| Accounts               | Mainnet                                                                                                               |
| ------------------     | --------------------------------------------------------------------------------------------------------------------- |
| Near on Eth Client     | [0x3FEFc5A4B1c02f21cBc8D3613643ba0635b9a873](https://etherscan.io/address/0x3FEFc5A4B1c02f21cBc8D3613643ba0635b9a873) |
| Prover on Eth          | [0x051ad3f020274910065dcb421629cd2e6e5b46c4](https://etherscan.io/address/0x051ad3f020274910065dcb421629cd2e6e5b46c4) |
| Ed25519                | [0x88f975d5a1153ea92af66e7c4292576a329c04b6](https://etherscan.io/address/0x88f975d5a1153ea92af66e7c4292576a329c04b6) |
| Erc20 Locker           | [0x23ddd3e3692d1861ed57ede224608875809e127f](https://etherscan.io/address/0x23ddd3e3692d1861ed57ede224608875809e127f) |
| ENear Locker           | [0x85F17Cf997934a597031b2E18a9aB6ebD4B9f6a4](https://etherscan.io/address/0x85F17Cf997934a597031b2E18a9aB6ebD4B9f6a4) |
| EthCustodian           | [0x6BFaD42cFC4EfC96f529D786D643Ff4A8B89FA52](https://etherscan.io/address/0x6BFaD42cFC4EfC96f529D786D643Ff4A8B89FA52) |
|Admin multisig         | [0x2468603819Bf09Ed3Fb6f3EFeff24B1955f3CDE1](https://etherscan.io/address/0x2468603819Bf09Ed3Fb6f3EFeff24B1955f3CDE1) |

Contracts are indeed not upgradable. Though the admin multisig may change the links to the sub-contracts that are called.

**Comment by luke7211** [comment]
If the multisig can change links to the sub-contracts, then technically (sub)contracts are upgradable
