### ISSUE TITLE
Change the Classification of ZKSwap from Validium to ZK Rollup

### ISSUE THREAD

**Issue by Isabella0319** [l2beat/l2beat#96]
Hi! ZKSwap is a project based on ZK Rollup solutions. Please help change the tech classification. Thank you! Here is the link to our contract:  https://etherscan.io/address/0x8eca806aecc86ce90da803b080ca4e3a9b8097ad

**Comment by luke7211** [comment]
Hi @Isabella0319 , can you please provide more explanation how zkSwap is a pure Rollup given that, as is stated here, some data is kept off-chain https://medium.com/zkswap/zkswap-introduces-practical-zk-rollups-zkspeed-achieving-high-tps-and-low-gas-fees-in-real-6effe4e789e0
